import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { SignedIn, SignedOut, SignIn, UserButton } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Your Site Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedIn>
            <header className="flex justify-end items-center w-full p-4 gap-4">
              <UserButton />
            </header>
            {children}
            <Analytics />
          </SignedIn>
          <SignedOut>
            <div className="flex min-h-screen items-center justify-center">
              <SignIn path="/sign-in" routing="path" />
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}